# Generated by Django 4.1.1 on 2022-10-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('idoficina', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('oficina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('codigoRFID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cc', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoRFID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.registro')),
                ('idoficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.oficina')),
            ],
        ),
        migrations.AddField(
            model_name='oficina',
            name='registros',
            field=models.ManyToManyField(through='Registro.RegistroOficina', to='Registro.registro'),
        ),
    ]
