# Generated by Django 4.1.1 on 2022-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='data_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
