# Generated by Django 4.1.1 on 2022-10-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_ingreso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingreso',
        ),
    ]
