# Generated by Django 4.1.1 on 2022-10-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
